openapi: 3.0.3
info:
  title: Ecommerce Platform API
  description: OpenAPI specification for the ecommerce microservices APIs.
  version: 0.1.0
servers:
  - url: https://api.example.com/v1
paths:
  /products:
    get:
      summary: List all products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal server error
    post:
      summary: Create a new product (admin only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created
        '400':
          description: Invalid input
  /cart:
    get:
      summary: Get user's cart
      responses:
        '200':
          description: Cart retrieved
        '404':
          description: Cart not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        image:
          type: string
        category:
          type: string
        stock:
          type: integer
    Cart:
      type: object
      properties:
        userId:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer